

export const users = {
    async post(req, res) {
        try {

        } catch(error) {
            res.status(500).send(`Erro interno do servidor!`)
        }
    },

}